[[services]]
name = "backend-service"
route = "test.local"

[[services.backends]]
name = "backend-1"
host = "127.0.0.1"
port = 3001
weight = 1

[[services.backends]]
name = "backend-2"
host = "127.0.0.1"
port = 3002
weight = 1
