[package]
name = "rev_proxy"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio.workspace = true
anyhow.workspace = true

pingora-core.workspace = true
pingora-proxy.workspace = true
pingora-load-balancing.workspace = true
pingora-http.workspace = true
pingora-error.workspace = true
async-trait.workspace = true
log.workspace = true
env_logger.workspace = true

config.workspace = true
